sudo: required
language: generic 
services: 
  - docker

before_install: 
  - docker build -t mjcloudguru/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true mjcloudguru/docker-react npm run test -- --coverage