sudo: required
language: generic 
services: 
  - docker

before_install: 
  - docker build -t mjcloudguru/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true mjcloudguru/docker-react npm run test -- --coverage

# Deploy on AWS
deploy: 
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-us-east-1-807692926958
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY